try { console.log('b'); } catch(err) {}